DISCOVERY_CAMPAIGNS = [
    {
        'name': 'snow_discovery',
        'maps': {
            "SnowIsBack": "01",
            "IcyHills": "02",
            "SnowGlider": "03",
            "WoodForce": "04",
            "WetWood": "05",
            "BreakOrSlide": "06",
            "IcySnow": "07",
            "WoodySlalom": "08",
            "Temple": "09",
            "SlippySnow": "10",
            "Hairpins": "11",
            "Rock&Revel": "12",
            "IAmSpeed": "13",
            "BobLover": "14",
            "SummerSnow": "15"
        },
        'season': 'fall',
        'year': '2023'
    },
    {
        'name': 'rally_discovery',
        'maps': {
            "RallyIsBack": "01",
            "RallyB1 Reloaded": "02",
            "BumpyRally": "03",
            "CastleWall": "04",
            "GrippyRally": "05",
            "NightWatch": "06",
            "NewSlopes": "07",
            "GreenStage": "08",
            "RallyC1 Reloaded": "09",
            "2laps2cars": "10",
            "Ralleigh": "11",
            "Dirt2024": "12",
            "RallyOnRoad": "13",
            "TransforMania": "14",
            "DeepEase": "15",
            "ClassicRally": "16",
            "Radium": "17",
            "WetRally": "18",
            "FrostyMorning": "19",
            "Rastic": "20",
            "Offroad": "21",
            "MixedStage": "22",
            "Snolly": "23",
            "IAmSpeed2": "24",
            "PowerStage": "25"
        },
        'season': 'winter',
        'year': '2024'
    },
    {
        'name': 'desert_discovery',
        'maps': {
            "DesertIsBack": "01",
            "PlatformJourney": "02",
            "Wiggle": "03",
            "DesertOnRoad": "04",
            "Originals": "05",
            "NewLoops": "06",
            "DesertC1Reloaded": "07",
            "A08Lover": "08",
            "DesertDirt": "09",
            "2Cars2Laps": "10",
            "GrassyDesert": "11",
            "DesTech": "12",
            "DesertCastle": "13",
            "Plasert": "14",
            "Dice": "15",
            "WoodyDesert": "16",
            "Narrow": "17",
            "AmericanSpeed": "18",
            "Halfpipes": "19",
            "DesertCity": "20",
            "WetDesert": "21",
            "2Wheelers": "22",
            "DesertLeague": "23",
            "DeseRPG": "24",
            "DesertMaster": "25"
        },
        'season': 'spring',
        'year': '2024'
    },
    {
        'name': 'stunt_discovery',
        'maps': {
            "StuntIsBack": "01",
            "SimpleFlips": "02",
            "Arena": "03",
            "SuperPipe": "04",
            "Stunt4Ever": "05",
            "Freedom": "06",
            "OriginalPark": "07",
            "A08Stunter": "08",
            "Lasagna": "09",
            "GiveMe5": "10",
            "AirMania": "11",
            "BumpersParadise": "12",
            "PlatformEdges": "13",
            "Moustache": "14",
            "RedAlert": "15",
            "Roundabout": "16",
            "Hiking": "17",
            "CibusFanaticus": "18",
            "SnowSpinning": "19",
            "Frikandelbroodje": "20",
            "HighSpeed": "21",
            "DeserticStunts": "22",
            "Foundry": "23",
            "StuntCity": "24",
            "ScatterPark": "25"
        },
        'season': 'summer',
        'year': '2024'
    },
    {
        'name': 'platform_discovery',
        'maps': {
            "PinkPlatform": "01",
            "Tangerine": "02",
            "Lemonpeaks": "03",
            "OrangeHills": "04",
            "Pipeline": "05",
            "Lagooning": "06",
            "Scarlet Summit": "07",
            "Glacial Plunge": "08",
            "Primula": "09",
            "Just Do It": "10",
            "Bulrush": "11",
            "Cobalt Cove": "12",
            "Caramel": "13",
            "Island Hopping": "14",
            "Padauk": "15",
            "Maple Mist": "16",
            "Coffee": "17",
            "Meep Mip": "18",
            "Backstroke": "19",
            "Hypothermic": "20",
            "Ceramic": "21",
            "ATFO": "22",
            "Deja Vu": "23",
            "Dance Of The Sugar Plum Fairy": "24",
            "ToThePink": "25"
        },
        'season': 'fall',
        'year': '2024'
    }
]

OFFICIAL_NADEO_AUTHOR_AND_SUBMITTOR_UIDS = { 
    "d2372a08-a8a1-46cb-97fb-23a161d85ad0",
    "afe7e1c1-7086-48f7-bde9-a7e320647510",
    "aa02b90e-0652-4a1c-b705-4677e2983003"
}

special_uids = [

    ## Structure
    {"uid": "", "name": "", "season": "", "year": "", "mapNumber": "", "alteration": ""}
]

all_TOTD_map_names = {
    "U-Turn",
    "Formule Gou1",
    "Desert & Forest",
    "Triforce",
    "Winterberg",
    "NéonDrift",
    "Symmetrixx",
    "Rainbow Road v2",
    "Mountain",
    "RGB-Road",
    "Lost Gate",
    "napaJ",
    "Summer Frost",
    "Yumi_05",
    "Tatooine",
    "Hanami",
    "handpan stadium",
    "Mighty Desert",
    "JoyRide",
    "The wormhole",
    "Sic Trackmanius Creatus Est",
    "Diversion",
    "Hanging Gardens",
    "Icy Cavern",
    "Route 66",
    "Drop THE CAVE",
    "Journey - Initial Climb",
    "steampunk 1877",
    "FS1",
    "Sand Drift",
    "SUBURBIA",
    "The Speedster",
    "Nascar Lakeside",
    "Night Slide",
    "Plain Sailing",
    "Melting away",
    "Outlandish V2",
    "Sakura",
    "S-02 Ring (v7)",
    "Oasis",
    "FuN",
    "Forgotten",
    "Howling Canyon",
    "Elements racing #1",
    "Future Valley",
    "Forced Slide",
    "Terracotta",
    "Saffron",
    "20 - Poison",
    "Green Day v2",
    "ђɇℓΐφş",
    "Journey - Eye of the Storm",
    "Mango Tango",
    "Fresh Air",
    "Paprika V2",
    "THERMALTECH",
    "Junglehouse",
    "Amethyst Castle",
    "C o d a",
    "Morocco",
    "Green City",
    "Juniper",
    "Hillside Highway",
    "Antarctica",
    "Doby",
    "cold hands",
    "NEO KYOTO MudaCup #1",
    "VELP - Mini - 02",
    "Airashī",
    "Undercover",
    "Mountaineer",
    "Hibiscus",
    "Nascar Phase 09",
    "Castle Assault",
    "Amarok",
    "Mountain Pass",
    "Outsider",
    "Invasion",
    "Desert Dunes",
    "Road Made Of Bread",
    "Edinburgh",
    "Skyline City",
    "BAY OF ISLANDS",
    "Time Warp",
    "Desert Fest",
    "SPECTRE",
    "Indiana Jones",
    "Goldrush",
    "Nascar Trainyard",
    "Parking Lot",
    "temple of the unknown",
    "Dino Den",
    "SANCTUARY ZERO",
    "In Via",
    "Sunken Desert City",
    "Greantea",
    "Avalanche!",
    "Fairy Drift",
    "Lost Village",
    "BAY",
    "Scar land",
    "Sriracha",
    "MAGIC CARPET",
    "A Land before Time",
    "Haunted forest",
    "Savage",
    "Valley Trail Turbo",
    "Hieme Iter",
    "Mars",
    "Journey - High Gardens",
    "Valley Ridamido",
    "GREENDAY",
    "Desert Dip",
    "ZOOM ZOOM",
    "Atlantide",
    "Space Launch",
    "Drift City",
    "Aardburn",
    "Aqueduct",
    "Green Hell",
    "Lost Eden",
    "ShortSwift",
    "TuplaJ Desert Mountain",
    "¬ aYobi «",
    "On The Edge",
    "Wadi",
    "Raiken",
    "Redwood Nascar",
    "All Terrain Vengeance",
    "MIDNIGHT METROPOLIS",
    "FRZ #7 - Bridges",
    "Woodland Circuit",
    "The Jaunt[FS]",
    "Funnel",
    "The Descent II",
    "Uphill",
    "Castle in the Sky",
    "SLAP Like NOW",
    "West",
    "Polaris (MTC)",
    "Coaster World",
    "Texas Angel",
    "Versailles Palace Nascar",
    "Kaleidoscope",
    "MTC - New World",
    "Frozen Valley",
    "BLIZZARD",
    "DAREDEVIL",
    "Nascar Vegas Earthquake",
    "Interchange",
    "Riverside",
    "The Circuit De Monaco",
    "Pretzel Precipice",
    "Islands",
    "Frosty Airfield",
    "DreamWorld",
    "Fairy Drift 2",
    "Arrakis",
    "Circuit Indianapolis #14",
    "Fury Road",
    "Abrupt Decay",
    "box2box",
    "Golden Age Nascar",
    "Vertigo",
    "Jumpy Jack",
    "Learn to fly",
    "breeze",
    "Jungle",
    "BURIED IN SAND",
    "Green washing",
    "E D G E  T R A N S I T",
    "VALHALLA",
    "Arches",
    "Take a Break",
    "Sztyeppe",
    "Desert Highlands",
    "Light In The Dark",
    "OPLONTIS CITY",
    "Daro Nust",
    "Climate Change",
    "Landslide",
    "Escape Hills",
    "ÐÐ Valley City 4",
    "Kilimanjaro Nascar",
    "Desert Speed",
    "VertDause",
    "NightFall",
    "Lagoon Cove v3",
    "Disposal",
    "Corrupted File",
    "Sandy Rupture",
    "Alien ISS",
    "Sugar Rush",
    "Going Deeper",
    "Metz",
    "Pearl of Gobi",
    "ÐÐ end world 4,1",
    "Freedom Valley",
    "BEE",
    "Frosty Riverside",
    "Hideout",
    "My Love Is Winter",
    "Xaruh",
    "Botanic Park",
    "Are you tough enough?",
    "Emerald#",
    "Peaceful'",
    "Descent",
    "v R a m",
    "Dragon's Lair",
    "tinyTurns",
    "SandyDunes",
    "Through the seasons",
    "EXILE",
    "Catnip",
    "ORBIT",
    "CrystalRoad",
    "Euphoria",
    "Drowning Obstacle",
    "Canyon Nascar",
    "MTC - Summit Run",
    "Island of Sunrise",
    "Firefly",
    "Raikanna",
    "Rapture",
    "Grip City",
    "ヨBǕKヨCЇ",
    "FOG",
    "OverGrown Evolution",
    "Lunar Expedition",
    "Lone Country",
    "Tropicana",
    "Speedfun Coast",
    "Soaring |  Terrace",
    "Everest",
    "Drift n' Cherry Blossom",
    "Konfians sé zié",
    "CornerTech-",
    "Hill down C07 4",
    "Terra",
    "MultiBiomes",
    "Délután",
    "Tomorrow's World",
    "HAMSTER MAZE",
    "NAC - Spire Garden",
    "Palm Beach Raceway",
    "PURE ZONE",
    "Hiking Trip",
    "Solstice",
    "Mountain Dew Evolution",
    "Luminous",
    "Equality",
    "Valkyria",
    "Mind Bending",
    "Maelstrom",
    "MOMENTUM",
    "Race on the clouds",
    "Snowland",
    "Slice of Life [V2]",
    "Elysian",
    "RETRO DRIFT",
    "Collapsed sea",
    "MTC - Yucatán",
    "Λ e t h e r   S y s t e m  (ぺオ偉）",
    "|Rustica",
    "Haru",
    "MTC | Oasis",
    "MTC - Green Canyon",
    "Siege",
    "Boxed FS",
    "The Chase",
    "Freedom",
    "Green washing 2",
    "Hidden Cave",
    "[LOL]Plinko v1",
    "MTC - Dawn Forest",
    "Pleochroism",
    "Ridge",
    "Inwards",
    "Evolving Minds",
    "Escape Velocity",
    "TEMPEST",
    "Ocean Nascar",
    "NAC - Good 'Nuff",
    "Le Pic",
    "MTC - Cavern",
    "DirtCare",
    "Myrtille",
    "SUBURBIA 2",
    "VERTIGO ²",
    "Graveyard",
    "DesolateDirt",
    "Deep Winter",
    "Hiraeth",
    "Four Seasons Evolution",
    "Sun Rays",
    "Tropical Archipelago",
    "Rothenburg",
    "RECKLESS",
    "Viking village",
    "Trackmania - Legacy",
    "Ecume",
    "MIXTA VIA",
    "Gravemind",
    "Cajarana",
    "Viridescent",
    "[NotRPG] The Sheepments",
    "Getcha_Anomaly",
    "green belt",
    "Vortioxetin",
    "Chasm of Mysteries",
    "Grand League",
    "The Chase 2",
    "Zephyr",
    "Piranha Bite",
    "!Under Construction!",
    "Deep Sea Diving",
    "millennium",
    "NAC - Icy Hollow",
    "Atoll Freight",
    "LUTHADEL",
    "Convergence",
    "retrograde",
    "Lost in the fog",
    "MTC - Eista",
    "The Movie Set",
    "AshyBravery",
    "Velocitas Cursus",
    "Viridi Gramina",
    "Far West",
    "Forsaken",
    "satisfice [ mtc ]",
    "RUNIC 1 - The Great Evil",
    "Infexus",
    "DirtingDancing",
    "miniLOL 03",
    "ILL-CONCEIVED",
    "Japan Vibes",
    "Telluriforce",
    "Snowfall",
    "Definitely not AnGeL",
    "Abandoned Island",
    "Pixel Chill",
    "Life Eternal v2",
    "MTC - Yeti",
    "Machina",
    "Meadow Lane (ft Neoriion)",
    "MELTDOWN",
    "Healing",
    "Pipe Rider",
    "Urban Circuit",
    "purple",
    "Re-Mixed",
    "Coaster - World Tour",
    "Aquaplaning",
    "Lullaby",
    "#ruinzz",
    "CONCRETE JUNGLE",
    "Winter Holidays",
    "plastique",
    "Asylum",
    "AXOLOTL MAZE",
    "TheCave",
    "WHITEOUT",
    "Plastech",
    "Perfecto Bonko Mapo",
    "LAKONIΛ",
    "MTC | TRINITY",
    "#zoomies",
    "Soul essence",
    "Eisen",
    "The Bank Robbery",
    "Blindness",
    "Vashj'ir",
    "VENTURE",
    "SOS | Laid Back",
    "Cinder Glade",
    "Black Blizzard",
    "ᅔᅀANCIENT RUINSᅀᅕ",
    "Chakra",
    "plastic beach",
    "Aerobatics",
    "[MTC] Cascadia",
    "juxtaPOSED",
    "AKITA 2 - HIKARI",
    "Aerii",
    "Crescendo",
    "Gimmick CE",
    "Fjord",
    "Backwards is faster, or is it?",
    "sapristi",
    "Muckraker",
    "Redpearl Resort",
    "Rio",
    "Abandoned Island",
    "Exotic Road",
    "Frozen Wastes",
    "BINARY",
    "TRACKMANIA 64",
    "Overload!",
    "Black Mamba",
    "Canyon Rush",
    "Early Bird",
    "Plastic Arena",
    "Poaceae ft' sláys",
    "Backside 270°",
    "Bikiny KØ",
    "Stargazing",
    "Chase the Lion",
    "PALM RUN",
    "Anima",
    "UpsideDown",
    "Sandstorm 2",
    "Ba|Sing|Se",
    "Black Pearl",
    "#rigged_",
    "Ephemeral",
    "Cold Warmth!",
    "Casino",
    "DeepRockGulch",
    "Heaven",
    "Cold Mist",
    "SERENITY",
    "smartLine",
    "F-ZERO NASCAR",
    "Opuntia Ft' Sláys",
    "Fortissimo",
    "Scroll Mania",
    "Havn",
    "Cascade",
    "Sculpture",
    "Copied City",
    "Boréas",
    "Asgard",
    "Ice bath",
    "Dark Sun",
    "Animus",
    "Crystalized",
    "BOING!",
    "Palombiana",
    "B A C K & F O R T H",
    "Plastikflüsterer ft Spammiej",
    "Spectral",
    "Skaftafell",
    "#ruins²",
    "Kairala",
    "Arboretum",
    "Chill Out ft Berzerk",
    "Aftermath",
    "LEMONADE",
    "Tatsu",
    "Conflagrate",
    "Vanndalen",
    "Hakuba",
    "AKITA 3 - TSUKIMI",
    "Baloo",
    "Digitalis",
    "Glacial Gliders",
    "Blue Lagoon",
    "TECHNICA VIA Ft' HTIMH",
    "Dakor",
    "Solitary",
    "Silver Grove",
    "Ruby drive",
    "Mellonticos City",
    "INTERLAKEN",
    "MARS PRIMUS",
    "Eclipse",
    "Kokomo Island Raceway",
    "anew",
    "Slowflake",
    "The Chase 3 ft' ShcrTM",
    "Snøfjell ft Scarzor",
    "Crimson Aura",
    "Terbius Hollow",
    "Chroma's Purgatory",
    "#ruins³",
    "PANTHEON - ZEUS",
    "Phantasm Chasm",
    "tmx BASCO 2021",
    "AUTUMN DAYDREAM",
    "NAC - Return to Form ft RogueDawn",
    "altania",
    "Greenwood Fantasy",
    "Panthania",
    "Utgard",
    "Haunted Forest",
    "Castellum ft' Nightwolf",
    "PPGA - Ice Gokart",
    "Cadenza",
    "TORTUGA",
    "Trava ExTen",
    "Water Heart",
    "anisychia",
    "Parthenon",
    "Spirit Walk",
    "Red Mud",
    "Iverna",
    "Flyin' Cherry",
    "DWAYNE",
    "Erathell ft' kouks",
    "Lost Springs",
    "Salted Earth",
    "Tropical Valleys",
    "PANDORA (ft Osoguineapig)",
    "Howling Valley",
    "MITH ODASYNE Ft' Enysado",
    "Mick'ice (Ft Sympthome)",
    "Hallelujah Mountains V2",
    "Downtown (ft Urumi)",
    "Arapaima",
    "Urayne",
    "Sunshine",
    "Limnoula",
    "Fission Strike",
    "Overgrowth ft' Yamii",
    "Forsaken Factory",
    "Fujiyama",
    "CCP#01 - SILENT NIGHT FT' KEISSLA",
    "C o n s t e l l a t i o n s",
    "dabedi",
    "Schwanensee",
    "Kheopsis ft TheRealSike",
    "Zenith 72",
    "Conifer Creek",
    "Sinterklaas",
    "Bitterroot",
    "CCP#10 - You Better Watch Out",
    "Ahn'Tjaru",
    "CCP#12 - Winter Solstice ft' Vixxa",
    "Escapade",
    "CCP#14 - KlausCraft",
    "CCP#15 - De Alpen ft'Ealipse",
    "CCP#16 - Nippy Sailing",
    "The Wild West",
    "Chroma's Purgatory 2",
    "FireflyValley ft'Queen_Clown",
    "Flanza",
    "CCP#21 - Wrapped",
    "Headlands",
    "Acadia",
    "CCP#24 - Taiga ft' Osoguineapig",
    "L A    P O C H E Z Z A",
    "Wild Dingo",
    "2 lines",
    "Polarity",
    "WORLDS COLLIDE",
    "#alpine",
    "Pipephobia ft Nightwolf",
    "oops dropped my nachos",
    "Ville-Marie ft' Scarzor",
    "YAHFIR",
    "Contaminated",
    "Kretos",
    "Desert Shroud",
    "The Bridge Reversed",
    "Pompeii",
    "Moriko",
    "Mooving Man",
    "Oasis",
    "NORGARD",
    "Hike Trail ft' Nightwolf",
    "Curveball",
    "CCC2 - Pirate Slide",
    "The Showdown",
    "Eternal Snow ft' Ealipse",
    "Nascar Joyride",
    "Violet Radiance",
    "BorpaSpin ft BURLYpog",
    "Innocence",
    "Forest Awakening",
    "teflon V2",
    "Artificial Nature",
    "NATARUK",
    "Solis Occasum",
    "Cold Sweat ft' Scarzor",
    "Azur Chimera ft' Nightwolf",
    "Clifftop Retreat",
    "AURORA ORIENTALIS MTC",
    "#extraction",
    "Vertigo - Players Against a Magnetic Wall Full of Obstacles",
    "Amnesia",
    "FINDING SHORTY",
    "CMYK",
    "Rainy Day ft Newtron",
    "Driti leik",
    "tea in the evening",
    "Panna Cotta",
    "Nature's Claim",
    "Noxious Nostalgia",
    "#soapbox",
    "MTC - Woodkid",
    "Elysium City Dynasty",
    "Nation of Zaun",
    "Cloudcrest Lake",
    "Pokegama",
    "Shenandoah",
    "Dropveter",
    "Avocado",
    "Agitation ft' EntryLag",
    "#ruins'4",
    "Spinning Spatula",
    "Superposition",
    "Taiyo",
    "Five by Five (ft Kyle)",
    "Maracujá",
    "Vizima 'ft Vixxa",
    "Gaia ft Grymlock",
    "MTC - HabMichLieb Würfel",
    "Plasticity ft ShineluTM",
    "Ignis ft' ollernice",
    "AKITA 4 - KOYO",
    "Avalanche",
    "Gamer Impact",
    "Willy Wonka's Chocolate Factory",
    "AQUAPARK ft ' Sophie_ice",
    "Glory Days ft Neon",
    "Frosty creek",
    "Airflow",
    "Horizon Vista ft' Deadfish & Ozei",
    "Glendara",
    "Babylon ft niZe",
    "Skyfarer ft Oclavukixus",
    "Imagine ! - CE",
    "Marzipan ft' ripfish_",
    "Willesden",
    "Santorini",
    "Venomous Powerslide",
    "Stone - Factory feat Ice_TM",
    "Outer Edge",
    "Leviticus FT' WemZ",
    "BEACHSIDE PARADISE 2 edit 9",
    "Nightrealm",
    "Outlands",
    "GripClash",
    "Rorvik",
    "Airburst",
    "Riptide",
    "Chikyū",
    "Classic Pinball",
    "Halo",
    "Autumni Machina ft kouks",
    "Iverna 2 - Evolution ft Ealipse",
    "Botania",
    "Pandatorium",
    "Dachstein (ft Berzerk)",
    "Ipnu Rivulet",
    "Spa Petitchamps",
    "Future's Forge ft SparklingW",
    "Twilight",
    "Blurry Future",
    "Masquerade",
    "Faithless Evening",
    "Piplup",
    "Slopestyle ft Newtron",
    "Whale Trails - Ft Oclavukixus",
    "Staurolite",
    "Bobtech",
    "Sanharaja ft' Krnz",
    "#Wasteland",
    "Ambiguity ft' Xefas",
    "MALAISE",
    "HAVANA",
    "Indirted",
    "Biomorph",
    "Kingsday ft Henkisme",
    "Ether Chimera ft Ealipse",
    "Besu",
    "Aki no hiruma",
    "Eggflip",
    "Adhesion Zero ft' sophie",
    "Chaotic Energy",
    "Breathe",
    "Curiosity",
    "Aeturnis",
    "Point Nemo  ft deadfish",
    "PATCHWORK",
    "Guilty Conscience (ft Mephistö)",
    "Bonkphobia ft' Nightwolf",
    "Moulin ft' Rabbi",
    "Rooftop Secrets ft' shorty",
    "Adams Race",
    "Devil Don't Dance",
    "#Lighthouse",
    "[MTC] Mystic Rush",
    "Crispy Chilli Oil",
    "Gilneas ft' Vixxa",
    "| Champions Drift |",
    "Frozen Fury",
    "LIFELESS DIRT",
    "Balaena Ft Oclavukixus",
    "Smooth Criminal - ft elliot",
    "Hikone ft Nightwolf",
    "Crowd Favorite",
    "Route 66 (ft Berzerk)",
    "another backwards map ft proof_",
    "Oasis",
    "Plastech #6",
    "Tantoura - ft' microvert",
    "Saduga Desert -V2",
    "Summer Park ft Tomote",
    "Bullet Train District",
    "Poggadopolis 2033",
    "Garden Snake",
    "[MINI] WATA",
    "Welcome Home",
    "Fractured Dimension",
    "STRETCH ft dom",
    "Odarath",
    "Ceramic Terrace",
    "The Wurst Map ft proof_",
    "Mixed Feelings 2",
    "Alexander Salamander",
    "Skyline",
    "#fantasia",
    "Xatu",
    "Beachside Paradise 4",
    "BobSlee",
    "Kalahara ft' Xefas",
    "Ghostly Boardwalk",
    "MTC - Solstice",
    "Nassau",
    "sprout of hope",
    "[SIT] Technical Ice ft' Sympthome",
    "RAL5015",
    "New Orleans",
    "Sagano",
    "Mile Zero",
    "r a i n d r o p s",
    "Horus",
    "Happy Birthday",
    "Twilight",
    "Kanzan",
    "Black Jade",
    "Precarious",
    "UP & DOWN ft proof_",
    "Maya",
    "»ytrap loop«",
    "Skyholm - Ft Nightwolf",
    "Alpha Decay",
    "In The Shadow Of The Valley",
    "Scarlos",
    "Intertwisted ft Edamame",
    "TRICOLOR",
    "AKITA SLIDE",
    "Cloud Storage",
    "Mechаnic Вeeswaх",
    "Butter Kraft Mac",
    "Lost Oasis",
    "Cor'Beg 'ft Sophie",
    "Super 77",
    "#RUINS 5",
    "Midori",
    "Technical Endeavour",
    "Shefet Dunes",
    "GANEDEN II",
    "PANTHEON - POSEIDON",
    "CHROMA's HIDEOUT Ft Xefas",
    "Momentum",
    "Trojan Horse #fixed",
    "Blood Rush Inception",
    "[MTC] Eventful Descent",
    "Changing Perception",
    "LEMON NUCLEAR",
    "Incognita - ft ExoTicZ",
    "Lustrous Nightsky",
    "New Lumina ft' Ealipse",
    "Speed Highway",
    "Rebirth",
    "Frozen River",
    "Streamline",
    "Polar Pipeline",
    "Arapaima II",
    "WORLDS COLLIDE 2",
    "Forsari  ft contacT",
    "Grappa Ice",
    "#REDROCK",
    "WORK IN PROGRESS",
    "Perdita",
    "Aquatic Park",
    "BOGUS ft' MASSA",
    "Atmosphere",
    "Last Outpost ft Agrabou",
    "Rcadia Mix - Oxygen",
    "Ensorcellment",
    "OPUS",
    "Thunder||Storm",
    "Glacialis ft' Gioksz",
    "Balloon Skyline",
    "Tibet 西藏 - ft Zengo",
    "Jikan",
    "Croc Falls ft Brave",
    "Kacky of the Day",
    "Archipel ft Vixxa",
    "Circuit Zandvoort",
    "The Iron Giant",
    "HydroPower",
    "Wood Hammer",
    "VANILLA SKY",
    "Saba ft' XLRB & Henk",
    "Mystify",
    "Sunken Treasure",
    "Eternity, But Everywhere",
    "Bloody Mary",
    "Deus Ex Machina",
    "Aqua   ft' Mephistö",
    "WaterGliders",
    "Ascent ft kiMi",
    "Reddas'",
    "Reality Falls",
    "Blue Riptide",
    "Grassy seed",
    "Back To The Present",
    "WIND CHILD",
    "MirrorWorld",
    "MARDI GRASS",
    "Protocol 783-A",
    "TMFL - Chichén Itzá",
    "ICE-o-Dice-O",
    "Wuko '",
    "Cloverfield Drift",
    "Shaky Sands ft' Henkisme",
    "Royal Fiesta",
    "Verdigris - ft' Loon",
    "Blood Rush Akira",
    "Once in a Blue Moon",
    "Water Bound",
    "Merciless",
    "Pé do Home",
    "XNO ft man0x",
    "MECHANICAL DAWNS  [ 4 ]",
    "NEO-CUPRA - DIGITAL CIUDAD",
    "Egrillaer ft' Scarzor",
    "Temple of the lost god",
    "C'cL Axiom ft KyleA «",
    "MaoBikzy -Desert",
    "Penguin Slide",
    "Castello Arcobaleno ft Queen_Clown",
    "it's a bit windy up here",
    "Form Factor ft' Scarzor",
    "Space Junk",
    "High Above",
    "funkyminimulti#1",
    "NAC - Taste of Fall ft' Calagaaan",
    "Estis Torealis",
    "NEO-CUPRA - DIRTY BIG BLUE",
    "NAC - Camelot",
    "Royal Garden ft' Kerberos&OregoX",
    "Glacier Slide",
    "VITALITY CE ft' RogueDawn",
    "United",
    "Ambrosia",
    "Trick'r'Treat",
    "Formula Surf",
    "Horizon Vista 2 (Night)",
    "Watern't 2",
    "Sapphire",
    "Dystopia - Flowstate",
    "Reminiscent",
    "NEO-CUPRA - GO FAST OR DON'T RACE",
    "USA - Tempus Ft Oso",
    "Capybara ft Henkisme",
    "Niepodlegli (ft mime)",
    "Backwards Progression ft AgentWhiskey & Henkisme",
    " Cut Down ",
    "Hyperion's Retreat ft' Ski Freak",
    "Put it in reverse!",
    "Rekindled Memories ft Spammiej",
    "Polymer Playground",
    "Dust to Dust",
    "Shark Tiger Ft NineToFiveGamer",
    "Biosphere",
    "Bellissimo ||| Bay",
    "NEO-CUPRA - TRANSICIÓN",
    "Apotheosis",
    "Glacial Storm",
    "Crimsoned",
    "Parakeet ft AlsenW",
    "Lucidity",
    "Canyon Chase (NFS Carbon Tribute)",
    "Cochise",
    "Aoraki",
    "el Jardin",
    "CCP#01 - Antifreeze ft sláys",
    "FSOTW | Celer",
    "Lakeside",
    "AZUL",
    "NEO-CUPRA - CURVAS VERDES",
    "Tawasaki (ft' Bren)",
    "Vile Jungle",
    "Escher's Sanctuary",
    "FSOTW | VORTEX",
    "Elemental Equilibrium",
    "scrambled ft eggs",
    "Deformative|Ξ",
    "SnowSlide ft Contact",
    "Areonyx ft' Dot",
    "Freezing OVER (FT OHIO_JG)",
    "!!",
    "MTC - Alta Neu",
    "Watern't 3",
    "Flipping Gravity",
    "CCP#20 - Aurora ft Whiskey",
    "CCP#21 - Jingle Industry",
    "CCP#22 - Santa’s Sleigh",
    "CCP#23 - Firnification",
    "CCP#24 - The Night Before Christmas ft' Zengo",
    "CCP#25 - Blåfjell ft' Scarzor",
    "'|Ethereal Islands ft' Alsenw|'",
    "PROTOGRADE",
    "Hovy",
    "Pastel Overture ft' Opale & 9to5",
    "Sombrero Escalero",
    "Shen-zin Su Ft Ealipse",
    "Deterministic Deep Dip",
    "Tencho ft' Intax",
    "Tachycardia",
    "Eternity",
    "Lightrider",
    "Mountaintops Of The Giants ft Henkisme",
    "verses of poetry",
    "Violacei Lapides ft alexS",
    "NEO-CUPRA - REAL FAKE GRASS",
    "'ACROBATECH!",
    "Night Air",
    "Genial Gardens",
    "Flare ft Giilo",
    "Jötunheimr ft Capman",
    "midriatel",
    "Changes Ft OHIO_JG",
    "Howl's Moving Castle",
    "Vanilla Sky",
    "Kōri no awa",
    "Toxic Paradise",
    "soarenity",
    "Dissolution",
    "NEO-CUPRA - ICY FLIP",
    "[LGZ] Slippery",
    "Apricot Ft Westcomb",
    "Fish Dreams  Ft Oclavukixus",
    "Persian Trail",
    "Aftershow",
    "EROS LITE",
    "Esper ft mime & Isirix",
    "Flynt  ft Skofus",
    "Forgotten Ice",
    "Downside Up",
    "Geometric Valley",
    "Black Rose ft KarjeN",
    "Megalospoly ft' Henkisme & Vixxa",
    "NEO-CUPRA - THE GREAT CLIMB",
    "Revel",
    "Lanturne",
    "Unfolding",
    "God Valley",
    "MTC - Artemis 11",
    "Urban Uphill ft Rabbi",
    "'|Diversity ft' Contact|'",
    "FS FANTASY",
    "Master of None",
    "Overgrown Shrine ft Henri97",
    "Drum Beating",
    "Chances Knife",
    "Summerland",
    "NEO-CUPRA - MAGNETIC MAZE",
    "Ab Undis Viridibus",
    "STARS OF GLORY",
    "Dissonance",
    "The Fisherman",
    "Insomnia",
    "Ice Cold",
    "A summer evening",
    "AOCC2 || Kenangan",
    "KEKL  - Another Rainbow Road",
    "Humble Hollow",
    "how will we get down",
    "Alkeline",
    "Fracture",
    "NEO-CUPRA - SUSPENDIDA DRIFT",
    "Forget-Me-Not (ft' agrabou)",
    "Stratus ft orbittall",
    "Verdance ft' Westcomb",
    "X Fsn't ft' Xefas",
    "Maho$ gany ft' XLRB",
    "Mercury",
    "[WRL] -  Bioengineered",
    "Steel Symphony",
    "Treetops Terrace ft' deadfish",
    "Trust Issues V2",
    "Buckled Gardens",
    "Lost Archives Ft Sp4ck0",
    "Monochrome Autodrome ft Henkisme",
    "NEO-CUPRA - CHAOTIC SPACE",
    "Dream Emotions +",
    "Lets burn some rubber!",
    "Double Take",
    "Slick Circuit",
    "Totodile ft' Jackmania",
    "ParkDrive ft' WISPschlumpy",
    "Hallelujah Mountains ft Orbittall",
    "Isengard",
    "Forgotten Island",
    "gyrtex",
    "Shaky Sands 2 ft' Henkisme",
    "Splashdown speedway",
    "FROSTNOVA",
    "NEO-CUPRA - ÚLTIMO GALACTIC RUSH",
    "Cowboy Shower",
    "Crisp",
    "TECHIES",
    "AJAX",
    "CENOTES",
    "Cuélebre",
    "Content",
    "Blossom Industries",
    "Neon Zen",
    "FS at Home",
    "MilkyWay",
    "Duplicity",
    "Cyndel '",
    "Reimagined Dreamscapes",
    "Kap Trelawney",
    "[zak] Concrete Dreams LITE",
    "Final Rush",
    "Sylvan",
    "bserver",
    "Damn Homie (ft Massa)",
    "ATOMIC ASCENT ft' Nazgor",
    "Lavender Haze",
    "The Milk Man (Safe)",
    "Knock Turn All",
    "Flora Path ft' speq",
    "Pumpkin Pie",
    "Babylone",
    "Maze of the day",
    "Crossroads",
    "Nivelleth",
    "the evokers",
    "Weides - ft' Gommettes",
    "Python",
    "Mesura ft Rossa-",
    "[Mini-RPG] The EPIC CHICKEN QUEST",
    "A Moment of Clarity",
    "Nika",
    "BROKEN CITY   ft Contact",
    "Fingal's cave reopened",
    "Poly Bridge",
    "Construction Canyon",
    "Gilneas - The Market",
    "Vitascope",
    "Desert Spine",
    "Valhalla",
    "UNDISTURBED",
    "Seasonal Sprint",
    "Tiefschnee",
    "Infrared ",
    "Louxoria",
    "Recycle",
    "Childhood Dream ft' XLRB",
    "Roof Edges",
    "Where is my Tuna",
    "Life goes on",
    "CRAINN SA SPÉIR",
    "AetherWorld",
    "Rubicante",
    "Planet Magnet",
    "Ampling Spheres",
    "Barren Labs Ft Oclavukixus",
    "Cloud Tech [ft Dunning & Kruger]",
    "Laminar",
    "Duststorm",
    "Ooroboros",
    "Permafrost",
    "Wirewood ft MattDTO",
    "Water Tower",
    "Serendipity",
    "Minas Morgul",
    "Mirai ft' Lackadal",
    "Shadowfall",
    "Escape",
    "Immortal Gardens",
    "Aether",
    "Hydro Forge Ft Neon & Ocla",
    "AC Mirage - Leap Of Faith",
    "Whisper of the Heart",
    "Fairy Tale",
    "Paradigm",
    "Dungeon Dash",
    "#Lighthouse²",
    "Summit",
    "Growth's Embrace  [CE]",
    "Pasture ft'DoogieMD",
    "Hebra Peak",
    "Mountain Road 10",
    "Aeravale ft' Ocla",
    "LOL AquaBunny",
    "SOFTCORE",
    "Oka'Yeg",
    "Jamaican Meadows ft Testman",
    "Wafer Gardens",
    "Antiquity ft Microvert",
    "Engulfed",
    "Blueberry Yogurt",
    "Crystal Dawn ft' Voltus_NL",
    "Asmarelo - Ft KrisTM",
    "Breezy Peaks",
    "Kedai",
    "Ignis Solaris ft' mime",
    "Vaporwave",
    "Save the Alamo",
    "Village in the Hills",
    "EyeOfTheStorm",
    "FUTURELAND CUP",
    "Mountain Melancholy",
    "Hiekka",
    "BACKSTAGE",
    "mélanj",
    "VOYAGE",
    "Hazing",
    "Prismal Path Ft Lowkeycuteboy",
    "Revving Up the Bricks",
    "Adriatic coasting",
    "AnGeL lol#12",
    "Distraught",
    "Flamingo CE",
    "Oriflamme",
    "PodRacer",
    "Night Sweets",
    "Troubled Spirits",
    "_Settled_",
    "-Hollow Hill",
    "Kεkλadεs",
    "enjoy your life",
    "Swelter Skelter  ft' Ascki",
    "bevel",
    "Flamingopolis ft' agrabou",
    "Climb",
    "ELYSIUM ft Logon13 & Avondale",
    "Particle Accelerator",
    "Jungle Trail",
    "Aeronautica Ft Oclavukixus",
    "Green_04",
    "Plastic Ride!",
    "Kacky of the Day #2",
    "Midsummer",
    "Pipecicle",
    "Nexus",
    "skyflare ft xEmlanx",
    "Celsius 18",
    "Leaf Links",
    "desert line",
    "ToyMania Kitchen",
    "Crème Brûlée",
    "mudded",
    "WHYTE",
    "MIXED  FEELINGS",
    "Polar Outpost",
    "Marbles of the Day",
    "Landstrasse 7",
    "Autumn Storrm",
    "CUPRA NEO-TRACKS",
    "RACE TO STaDOS",
    "Velocity Valley ft aBadPCGamer",
    "Northwatch CE | ft Sapph",
    "Wire",
    "Milo",
    "Alkaline",
    "Isolated Space",
    "Amber Rush",
    "Black & White",
    "d I S S I d E N T",
    "The Sleeping Kingdom",
    "Pomidore ft' Sanyikaa",
    "Avatar",
    "Eozal Ft Choum",
    "FLEDERMAUS",
    "Snowball ft' Linh x xEmlanx",
    "Immortal Gardens 2",
    "XPEvo - Cramptés ft' Henk",
    "Void",
    "Coiled",
    "Scourge Island",
    "Crimson Lights",
    "Simioid ft Brummba",
    "Phosphorus",
    "Kukuroo Mountain",
    "BOB",
    "Colourise",
    "Lost Soul",
    "caelid ft' microvert",
    "C e l e s t i a l   C i t y",
    "AC Mirage - Happy Launch",
    "Fishscape",
    "Plastum ft SoulDrinker27",
    "Bellösnag",
    "Ruins of  Resolve",
    "BLUE-STEEL",
    "TUYA [CE]",
    "Sky Beach",
    "Zaunover [CE]",
    "Sora ft' C0NLUSION",
    "Hikasa Vega Light",
    "Khione Ft' XLRB",
    "Blue Horizon",
    "CHUKCHI",
    "Pickled Onions",
    "petals",
    "Purify",
    "Glacial Station",
    "Laserhawk - Laser Speed",
    "Blevros SR",
    "Symplegades ft'Vixxa",
    "Magma Cavern",
    "PRINGLES GAME NIGHT",
    "-Black-Pink-",
    "Perfect Chaos",
    "Death Egg Robot",
    "Pumpkin Patch",
    "Swampy Slide",
    "Veritas ft' Raveout & Dot",
    "Mystic Sands",
    "Precious",
    "Saturation",
    "Coohl Mép",
    "Accidentally ft DoogieMD",
    "Continuity [CE]",
    "RENTA",
    "Bluefin Tuna",
    "Sage",
    "Board Track Challenge",
    "Blackpool",
    "Podrace of the day",
    "Yomp FT' Habe",
    "BOCORKA",
    "CyberPeach",
    "AlichinO",
    "BLALAMO [CE]",
    "Zeta",
    "20 years later",
    "Snow of the Day",
    "Aistoth",
    "animus aequus",
    "Raid",
    "Bitter Springs ft Bonneville",
    "SNØFNUGG",
    "O N Y X",
    "alsa phylaca",
    "Wind of Change",
    "Turtle of The Day ",
    "CCP#02 - Pagoniemi ft SirTalyon",
    "FrostFlare",
    "Manzanilla",
    "VALLEY LAKE",
    "SHURIMA ft sqweegel",
    "Joel's Hideout",
    "York ft' agrabou",
    "Dolphin Lagoon ft Oclavukixus",
    "Fondant",
    "EROS II DISTRESS",
    "Coast 1212",
    "Talvi",
    "Maple Rush ft Sp4ck0",
    "Rocky Mountains (CE)",
    "Bastet Ft' Zentrian",
    "Tokyo Drift",
    "Project Zero",
    "Downhill 3",
    "Blue|Monday",
    "PROMETHEUS ft. archer-2",
    "DTC - Muddy  Pipeways [CE]",
    "Nyctorchis",
    "CCP#24 - Northpole ft'Vixxa",
    "CCP#25 - Yuki no tera ft' Calagaaan",
    "'Tis a Tight Turn",
    "Luxor",
    "Exercise",
    "Cadmium (ft IguanaParty)",
    "Snow Peak v2",
    "HellTech",
    "Track-machines#1",
    "Rankine 511",
    "Bubble Bath",
    "Nitrogen",
    "LAST LIGHT",
    "Bing Chilling",
    "Mt' Inversion",
    "AKKI ft Vayq",
    "YukiMarimo ft' Kcedus",
    "Erosion ft' Clearvision",
    "Molenaar",
    "OutCast",
    "Ellie's adventure  ft Ascki",
    "NUN SVART",
    "Ascend",
    "Irish Goodbye",
    "Stonewashed ft Ski Freak",
    "Cytosine nerf",
    "BLACK & yellow",
    "Mania ft Ascki",
    "YAYO",
    "A Space Odyssey 2",
    "Draco's Time ft' Svendsenz & MrOmkes",
    "Centenarian",
    "Split Second",
    "Red Fury ft Skweeky2",
    "SwitchBack ft' SoulDrinker27",
    "Fever",
    "°Néréide*",
    "Ulna ft' Habe",
    "Eruption",
    "Arctic Temple",
    "culmination",
    "Misty Overhang",
    "HiddenLagoon ft' Popouette",
    "HUNGRY - SHARKS!",
    "Jörmungandr ft' BirdieTM",
    "Orange-Jade",
    "Grass Track",
    "Hesperian Ft Skweeky2",
    "Azure",
    "SnowDrift Ft Oclavukixus",
    "Orin",
    "Poolspeed",
    "Jaded",
    "Bridge Conduit",
    "a z u r i a",
    "Resort",
    "Rainy Racing",
    "Lyserød",
    "Undercover-Base-1D1",
    "Cinematica ft Microvert",
    "CORRUPTION",
    "Niraeth",
    "ToonTown ft MrPepsy",
    "Zeno",
    "Type X - RadioActive",
    "Castle Special Stage",
    "Kem's Castle ft XLRB",
    " DETONATE",
    "Nächtlicher Waldweg",
    "PaperCraft",
    "EXPO EXPO",
    "Reduce, Reuse, Rehash",
    "Gelifracción ft xPPHx",
    "S k y d u s t",
    "MotionSickness ft xGryph",
    "[Immure]",
    "Anyone's Past - Somebody's Future",
    "Scorched ft' Kcedus",
    "NOVA AGRI",
    "Bocorka Dreams",
    "Gardenium 4",
    "Before The Thunder [CE]",
    "Static Field ",
    "UTOPIA",
    "superficial",
    "Disintegrated ft' Ealipse",
    "TurtledSpeed+",
    "Periwinkle",
    "Silent voices",
    "Duckies Kingdom",
    "Graslkufs ft' green-K-",
    "Sonnema",
    "outlander»",
    "Rift G-Diddl",
    "TICKLED PINK",
    "CloseCombat",
    "Mango",
    "Formula E - Tokyo E-Prix",
    "Outpost- OASIS",
    "Mystery Route",
    "Venice Outrun",
    "Enjeru Tō  ft xPPHx",
    "blue yonder ft' Loso",
    "fika ft xJKlyS",
    "Dealership",
    "DTC - Symphonic Desolation ft Numberplay",
    "Forstweg 5",
    "Grysskaal",
    "DamageD",
    "Gardens of March",
    "Blanco ft' Hiko",
    "Canyon Cascade",
    "Nullentropy",
    "Morgana",
    "ultima ft' microvert",
    "Cave Dwellers",
    "Sini",
    "Electropolis",
    "silent tempest",
    "Starscape",
    "Dynamo",
    "Samsara",
    "chrysographes | ft djabski",
    "Counterpoint",
    "John Dirt",
    "Rollercoaster Beach",
    "kryptonite",
    "Magnesium",
    "Radioactive Ruinzzz",
    "FloorOfTheDay",
    "anomaly",
    "Calm Before the Storm",
    "XOR ft' Norbinarius",
    "Polygon Valley",
    "Belgica ||| 2086",
    "GP Kyōto 2049",
    "Old School 2020",
    "Trinity of Trackmania",
    "[Mrotw Ultimate] Explore",
    "Formula E - Berlin E-Prix",
    "Tantrum",
    "Lapislazuli",
    "Polar Plaza ft Moonstruck",
    "Printemps",
    "Salt Water",
    "Back to the roots",
    "Southern Horizons",
    "klauter",
    "Ethereal Sky",
    "S c a r m i g l i o n e",
    "Retro Revival",
    "Triple Threat",
    "Blim",
    "Misty Morning",
    "Banana Meltdown",
    "Tropical Sky",
    "MirARTa",
    "Ranchpoint ft' Mime",
    "DivineAbyss",
    "Island Odyssey",
    "SLOTMANIA",
    "C a r m i n",
    "BananaSPLIT",
    "Towers of Krios ft' Oclavukixus",
    "RGB",
    "Botanica",
    "Overwhelming feelings  or the illusion of free will",
    "Osan Apata",
    "Ayunda",
    "Cobalt ft' Hendo",
    "Hazing | ft' djabski",
    "EDEN's CIRCUIT",
    "Terrene ft' Westcomb & Ninetofivegamer",
    "TFH - Flooded Lands",
    "Careening Cliffs",
    "GP Sao Paolo 2031",
    "Walk in the Park",
    "IMLADRIS CE",
    "Jurassic valley",
    "Fort Prominence ft PChimpin",
    "TerraTrio",
    "Limgrave ft Pooeeee",
    "Starforge",
    "Atrick's Paradise",
    "Zaturn",
    "Ultramarine",
    "Premonition ft Sampler",
    "Orchidaceae",
    "$uTEAL TIME",
    "Sanharaja 2 ft' Nikel",
    "Looping Through Spring",
    "Lost Ruins",
    "Dichotomy {CE}",
    "Tunnel Vision",
    "LIGHTHEARTED",
    "DeFrost",
    "Pastlife",
    "Elysian ft Whizzy",
    "ODB",
    "Vinyl ft' Hiko",
    "Serenata ft Microvert",
    "parallax | ft Kaii",
    "Night's Provocation",
    "Reflected ft Trunckley",
    "Agraculture",
    "Summer's Slide",
    "Clockwork",
    "BERATOZ",
    "Mauve & Moss ft Rabbi",
    "overshadowed by ego ft' Lackadal",
    "Formula E - London E-Prix",
    "Life",
    "Somewhere Only We Know",
    "Lightenup",
    "Camping Trip",
    "RHOZE",
    "desolate distance",
    "Printstream",
    "Pyramidori ft Oclavukixus",
    "Floating Castle",
    "SERENITY",
    "Woodslide 2045",
    "Of Sausage and $ Scaffolding",
    "Epiphyllum",
    "Shandora ft' Intax",
    "Outlaw",
    "Quantum Leap ft Mime",
    "Coincutter's Haven",
    "Violet Reaper ft Atrick",
    "Begg",
    "cho oyu ft' link [SE]",
    "Plastikaner",
    "- Citronelle -",
    "AstraTrails",
    "Etherneal",
    "Jack of all trades",
    "blossom",
    "SSX - Sun Ridge Summit",
    "ØKOLOGI",
    "Eldar",
    "Woody Woodtecher ft' Intax",
    "Impress",
    "Oil Rig",
    "Paranoid (Because a Jellyfish is Spying on Me)",
    "p r o p a n e",
    "Grimevine",
    "GET A GRIP",
    "Xanadu",
    "ÆternΛ",
    "dustpark",
    "Thank You",
    "llehtarE ft' saghzs",
    "Broken Transmission",
    "SkyTropical",
    "GENERATIONS COLLIDE $kft' mime",
    "Amberoid ft' Hashbjorn",
    "John Grass",
    "RallyRush",
    "Disconnect",
    "Meadow Mayhem",
    "Cholla Springs",
    "Inane ft Voltus",
    "Retrograde ft' inv4lid",
    "Viridis Vallis Ft Oclavukixus",
    "Arctic Nightrush",
    "Constella ft Iesauka",
    "Jeskai",
    "LUMIX",
    "7DS - Gluttony",
    "Fekl of the day",
    "Menagerie",
    "Vanilla Constructions ft Tag6661",
    "Escape from SECTOR 21",
    "Industry Line",
    "SLIDELANDS 2",
    "Melting Point  | ft Drifter",
    "cereza",
    "Terra Purpura ft' NielsDewitte",
    "Somnium Noctis",
    "Iridaceae",
    "[REVIVAL] - PASSION",
    "Pannekoekenmix ft' Rotcat",
    "Snice",
    "Shimmer",
    "P a t c h w o r k ft Soul",
    "Immolate",
    "Goldorak ft Nastibe",
    "XPEvo24 - Tutel",
    "Truskawka Cheesecake ft' Misha",
    "Alpina",
    "Tachyon",
    "ZAFS - Turbulent",
    "Pale blue sky ft' link",
    "CROCIERA blu",
    "Hyperion ft' Gommettes",
    "DAWN'S AWAKENING",
    "BRICK MOSAIC",
    "SendIt",
    "Spook ft' Robbalobb",
    "TFH - Below the Stratospires",
    "Anodized ft Grogger",
    "Fresh Cut",
    "Kiitospäivä",
    "Crimson's Call ft Casual_Pequod",
    "GHRYZ",
    "Essence",
    "Training Grounds",
    "Synthetic Drift",
    "MTC | Track or Treat",
    "Harvest Shroom",
    "Carcassonne ft' Bren",
    "Last Whisper ft' aZix | Arien | Entrylag",
    "Gothic",
    "Kacky of the Day #3",
    "Back'N'Forth",
    "Valley Highway",
    "ENGAGE",
    "Into the Breach",
    "Chiaroscuro",
    "Violet Distortions",
    "Frozen blaze",
    "KOLMAS",
    "amuse-bouche",
    "WhiteSpire 'ft PhilTM",
    "Celsius 41",
    "WICKED!",
    "Controllah",
    "DreamWave Drive",
    "Bara",
    "ZAFS - Recluse",
    "Vertical",
    "Emerald Pass",
    "the glory of innocence",
    "steel monopoly",
    "Blueberry",
    "DropShadow",
    "Tachysensia ft' Narbex",
    "KING of DIAMONDS",
    "Sandsmoke",
    "Fluctuate ft tryhardnubs",
    "Summer Vibes",
    "Peachy",
    "Remorse ft' gjkf"
}