void SelectAlteredSurface() {
    IsUsing_Dirt = true;
    IsUsing_Fast_Magnet = true;
    IsUsing_Flooded = true;
    IsUsing_Grass = true;
    IsUsing_Ice = true;
    IsUsing_Magnet = true;
    IsUsing_Mixed = true;
    IsUsing_Penalty = true;
    IsUsing_Plastic = true;
    IsUsing_Road = true;
    IsUsing_Wood = true;
    IsUsing_Bobsleigh = true;
    IsUsing_Pipe = true;
    IsUsing_Sausage = true;
    IsUsing_Underwater = true;
}

void SelectAlteredEffects() {
    IsUsing_Cruise = true;
    IsUsing_Fragile = true;
    IsUsing_Full_Fragile = true;
    IsUsing_Freewheel = true;
    IsUsing_Glider = true;
    IsUsing_No_Brakes = true;
    IsUsing_No_Effects = true;
    IsUsing_No_Grip = true;
    IsUsing_No_Steer = true;
    IsUsing_Random_Dankness = true;
    IsUsing_Random_Effects = true;
    IsUsing_Reactor = true;
    IsUsing_Reactor_Down = true;
    IsUsing_Slowmo = true;
    IsUsing_Wet_Wheels = true;
    IsUsing_Worn_Tires = true;
}

void SelectAlteredFinishLocation() {
    IsUsing_1Down = true;
    IsUsing_1Back = true;
    IsUsing_1Left = true;
    IsUsing_1Right = true;
    IsUsing_1Up = true;
    IsUsing_2Up = true;
    IsUsing_Better_Reverse = true;
    IsUsing_CP1_is_End = true;
    IsUsing_Floor_Fin = true;
    IsUsing_Inclined = true;
    IsUsing_Manslaughter = true;
    IsUsing_No_Gear_5 = true;
    IsUsing_Podium = true;
    IsUsing_Puzzle = true;
    IsUsing_Reverse = true;
    IsUsing_Roofing = true;
    IsUsing_Short = true;
    IsUsing_Sky_is_the_Finish = true;
    IsUsing_There_and_Back_Boomerang = true;
    IsUsing_YEP_Tree_Puzzle = true;
}

void SelectAlteredEnviroments() {
    IsUsing_Stadium_ = true;
    IsUsing_Stadium_Wet_Wood = true;
    IsUsing_Snow_ = true;
    IsUsing_Snow_Carswitch = true;
    IsUsing_Snow_Checkpointless = true;
    IsUsing_Snow_Icy = true;
    IsUsing_Snow_Underwater = true;
    IsUsing_Snow_Wood = true;
    IsUsing_Rally_ = true;
    IsUsing_Rally_Carswitch = true;
    IsUsing_Rally_CP1_is_End = true;
    IsUsing_Rally_Underwater = true;
    IsUsing_Rally_Icy = true;
}

void SelectAlteredMulti() {
    IsUsing_Checkpointless_Reverse = true;
    IsUsing_Ice_Reverse = true;
    IsUsing_Ice_Reverse_Reactor = true;
    IsUsing_Ice_Short = true;
    IsUsing_Magnet_Reverse = true;
    IsUsing_Plastic_Reverse = true;
    IsUsing_Sky_is_the_Finish_Reverse = true;
    IsUsing_sw2u1l_cpu_f2d1r = true;
    IsUsing_Underwater_Reverse = true;
    IsUsing_Wet_Plastic = true;
    IsUsing_Wet_Wood = true;
    IsUsing_Wet_Icy_Wood = true;
    IsUsing_Yeet_Max_Up = true;
    IsUsing_YEET_Puzzle = true;
    IsUsing_YEET_Random_Puzzle = true;
    IsUsing_YEET_Reverse = true;
}

void SelectAlteredOther() {
    IsUsing_XX_But = true;
    IsUsing_Flat_2D = true;
    IsUsing_A08 = true;
    IsUsing_Antibooster = true;
    IsUsing_Backwards = true;
    IsUsing_Boosterless = true;
    IsUsing_BOSS = true;
    IsUsing_Broken = true;
    IsUsing_Bumper = true;
    IsUsing_Ngolo_Cacti = true;
    IsUsing_Checkpoin_t = true;
    IsUsing_Cleaned = true;
    IsUsing_Colours_Combined = true;
    IsUsing_CP_Boost = true;
    IsUsing_CP1_Kept = true;
    IsUsing_CPfull = true;
    IsUsing_Checkpointless = true;
    IsUsing_CPLink = true;
    IsUsing_Got_Rotated_CPs_Rotated_90__ = true;
    IsUsing_Earthquake = true;
    IsUsing_Fast = true;
    IsUsing_Flipped = true;
    IsUsing_Holes = true;
    IsUsing_Lunatic = true;
    IsUsing_Mini_RPG = true;
    IsUsing_Mirrored = true;
    IsUsing_Pool_Hunters = true;
    IsUsing_Random = true;
    IsUsing_Ring_CP = true;
    IsUsing_Sections_joined = true;
    IsUsing_Select_DEL = true;
    IsUsing_Speedlimit = true;
    IsUsing_Start_1_Down = true;
    IsUsing_Supersized = true;
    IsUsing_Straight_to_the_Finish = true;
    IsUsing_Symmetrical = true;
    IsUsing_Tilted = true;
    IsUsing_YEET = true;
    IsUsing_YEET_Down = true;
}

void SelectAlteredExtraCampaigns() {
    IsUsing_TMGL_Easy = true;
    IsUsing__AllOfficialCompetitions = true;
    IsUsing_OfficialNadeo = true;
}